apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  labels:
    app: microservice
spec:
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: cargateway-container
        image: cargateway:1.0.0


      - name: userrating-container
        image: userrating:1.0.2

   
      - name: microservices-container
        image: microservices:1.0.1

 
      - name: carcatalog-container
        image: carcatalog:1.0.1



---
apiVersion: v1
kind: Service
metadata:
  name: microservice
spec:
  type: LoadBalancer
  selector:
    app: microservice
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 31000

